---

- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
  - file: name=/home/ansible/pull.txt state=touch
  - file: name=/home/ansible/{{ list }}.txt state=touch
    with_list:
    - text1
    - test
    - get
